/* ═══════════════════════════════════════════
   REVENUE TARGETS — from 2026 Cascaded Targets workbook
   Company target: KSH 1,000,000,000 (1.2B gross minus 300M running contracts)
   Division targets: gross workbook values (independent of company total)
═══════════════════════════════════════════ */
const TARGETS = {
  company: { total: 1000000000 }, // gross revenue target = 1.2B (see GROSS_TARGET)
  divisions: {
    DM: { name: 'Development Management',        code: 'DM', target: 100000000,  actual: 0 },
    CI: { name: 'Civil & Infrastructure',         code: 'CI', target: 400000000,  actual: 0 },
    MF: { name: 'Mechanical & Fabrication',       code: 'MF', target: 350000000,  actual: 0 },
    EA: { name: 'Electrical & Automation',   code: 'EA', target: 150000000,  actual: 0 }
  },
  byStage: [
    { stage: 'Concept Development',             pct: 0.0125, target: 21250000,     gm: 0.40 },
    { stage: 'Detailed Feasibility',            pct: 0.0450, target: 76500000,     gm: 0.30 },
    { stage: 'Structuring & Financing',         pct: 0.0025, target: 4250000,      gm: 0.30 },
    { stage: 'Planning Monitoring & Controls',  pct: 0.0450, target: 76500000,     gm: 0.30 },
    { stage: 'Design Development',              pct: 0.0800, target: 136000000,    gm: 0.30 },
    { stage: 'Procurement',                     pct: 0.1200, target: 204000000,    gm: 0.15 },
    { stage: 'Construction & Installation',     pct: 0.6500, target: 1105000000,   gm: 0.18 },
    { stage: 'Commissioning & Handover',        pct: 0.0050, target: 8500000,      gm: 0.20 },
    { stage: 'Operations & Maintenance',        pct: 0.0300, target: 51000000,     gm: 0.30 },
    { stage: 'Decommissioning',                 pct: 0.0100, target: 17000000,     gm: 0.30 },
  ]
};

/* ═══════════════════════════════════════════
   COMPUTED — never manual input
═══════════════════════════════════════════ */
const prob_ = d => {
  // Excel: P = T × U  where T = V+W+X+Y (sub-scores), U = stage progress
  // Won deals always = 1.0; Lost deals always = 0
  if (d.status === 'Won')  return 1.0;
  if (d.status === 'Lost') return 0;
  // Recalculate T from sub-scores when available (self-healing — ignores stale stored lk)
  const at = +(d.dealAttributes||0);
  const en = +(d.engagementTiming||0);
  const hi = +(d.historicalSuccess||0);
  const co = +(d.competitorLandscape||0);
  const hasSubs = at || en || hi || co;
  const T = hasSubs ? Math.min(+(at+en+hi+co).toFixed(4), 1.0) : +(d.dealLikelihood||0);
  const U = +(d.stageProgress||0);   // stage-based progress (U)
  if (!T || !U) return 0;
  return +Math.min(T * U, 1).toFixed(4);
};
const wv_   = d => +((d.estimatedValue||0)*prob_(d)).toFixed(2);

/* ═══════════════════════════════════════════
   HELPERS
═══════════════════════════════════════════ */
const fksh = v => v==null?'—':v>=1e9?(v/1e9).toFixed(2)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(0)+'K':v?v.toLocaleString():'0';
const pct  = v => v?(v*100).toFixed(0)+'%':'0%';
const probCol  = p => p>=0.7?'var(--green)':p>=0.4?'var(--amber)':'var(--red)';
const probIcon = p => p>=0.7?'▲':p>=0.4?'◆':'▼';
const stTag  = s => s==='Won'?'t-won':s==='On Hold'?'t-hold':s==='Lost'?'t-lost':'t-open';
const prioC  = p => p==='High'?'var(--red)':p==='Medium'?'var(--amber)':'var(--ink4)';
const DL  = {DM:'Development Management',MF:'Mechanical & Fabrication',EA:'Electrical & Automation',CI:'Civil & Infrastructure',ALM:'Asset & Lifecycle Management'};
const DC  = {DM:'var(--c-dm)',MF:'var(--c-mf)',EA:'var(--c-ea)',CI:'var(--c-ci)'};
const CHARTS={};
const mk=(id,cfg)=>{try{if(CHARTS[id])CHARTS[id].destroy();const el=document.getElementById(id);if(!el)return;CHARTS[id]=new Chart(el,cfg);}catch(e){console.warn('[dashboard] chart('+id+'):',e.message);}};
const CD={
  grid:{color:'rgba(0,0,0,.08)',drawBorder:false},
  ticks:{color:'#48463e',font:{size:9,family:"'IBM Plex Mono',monospace"}},
  tp:{backgroundColor:'#fff',borderColor:'rgba(0,0,0,.12)',borderWidth:1,padding:10,cornerRadius:8,
      titleFont:{size:9,family:"'IBM Plex Mono',monospace"},bodyFont:{size:12,family:"'Sora',sans-serif"},
      titleColor:'#48463e',bodyColor:'#17160e'}
};

/* ═══════════════════════════════════════════
   SIDEBAR TOGGLE
═══════════════════════════════════════════ */
let sidebarOpen = true;
/* toggleSidebar replaced by responsive version below */
// Close modal on Escape key
document.addEventListener('keydown', e => {
  if(e.key === 'Escape') closeMo();
});


/* ═══════════════════════════════════════════
   REALIZED REVENUE SCHEMA
   ─────────────────────────────────────────
   Schema for running contracts & earned revenue entries.
   Source: 2026_Running_Contracts.xlsx → EarnedRevenue sheet

   Fields:
     id           : string  — unique record ID (format: "rr_NNN")
     project      : string  — project / contract name
     client       : string  — client / billing name
     division     : string  — division code: DM | CI | MF | EA | ALM | OTHER
     divisionName : string  — full division name as in source workbook
     billingEntity: string  — SDG billing entity (SDG / GCL / SEP / SDG-UAE …)
     description  : string  — invoice line description
     amountKES    : number  — invoice value in KES (already converted from USD where applicable)
     amountUSD    : number  — original USD amount if invoiced in USD (0 if KES native)
     invoiceDate  : string  — ISO date "YYYY-MM-DD" of invoice
     paymentDate  : string  — ISO date "YYYY-MM-DD" of payment ("" if unpaid)
     status       : string  — "Paid" | "Pending"

   Notes:
     • amountKES is the single source of truth for all KES aggregations.
     • Paid = cash received; Pending = invoiced but not yet collected.
     • The speedometer on the overview page reads SUM(amountKES WHERE status="Paid")
       against the 1.2B gross revenue target (fixed: see GROSS_TARGET in pages.js).
     • Division "UNASSIGNED" = invoice rows without a division tag in the source file.
     • Division "ALM" (Asset & Lifecycle Management) is outside the 4 core divisions
       and is tracked separately in the revenue page but excluded from division KPIs.
═══════════════════════════════════════════ */
const REALIZED_REVENUE_SEED = [
  {
    "id": "rr_001",
    "project": "Jetty Installation Works",
    "client": "Client R",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SEP",
    "description": "Milestone payment",
    "amountKES": 115525.33,
    "amountUSD": 895.55,
    "invoiceDate": "2025-12-01",
    "paymentDate": "2026-02-20",
    "status": "Paid"
  },
  {
    "id": "rr_002",
    "project": "Logistics Centre Construction Supervision",
    "client": "Client AF",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SEP",
    "description": "Monthly retainer",
    "amountKES": 2662016.31,
    "amountUSD": 20635.79,
    "invoiceDate": "2025-12-01",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_003",
    "project": "Access Road Masterplanning",
    "client": "Client K",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "GCL",
    "description": "Interim certificate",
    "amountKES": 382466.5,
    "amountUSD": 0,
    "invoiceDate": "2026-01-28",
    "paymentDate": "2026-02-02",
    "status": "Paid"
  },
  {
    "id": "rr_004",
    "project": "Jetty Materials Supply",
    "client": "Client S",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "GCL",
    "description": "IPC 02",
    "amountKES": 390308.6,
    "amountUSD": 0,
    "invoiceDate": "2026-03-04",
    "paymentDate": "2026-03-09",
    "status": "Paid"
  },
  {
    "id": "rr_005",
    "project": "Access Road Design Review",
    "client": "Client J",
    "division": "EA",
    "divisionName": "Electrical & Automation",
    "billingEntity": "SDG",
    "description": "IPC 01",
    "amountKES": 253118.99,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "2026-03-26",
    "status": "Paid"
  },
  {
    "id": "rr_006",
    "project": "Depot Consultancy Services",
    "client": "Client V",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SDG-UAE",
    "description": "IPC 01",
    "amountKES": 784094.45,
    "amountUSD": 6078.25,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_007",
    "project": "Depot Construction Supervision",
    "client": "Client G",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SDG-UAE",
    "description": "Interim certificate",
    "amountKES": 19744592.94,
    "amountUSD": 153058.86,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_008",
    "project": "Depot Site Assessment",
    "client": "Client N",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG-UAE",
    "description": "Monthly retainer",
    "amountKES": 1524570.34,
    "amountUSD": 11818.37,
    "invoiceDate": "2026-01-13",
    "paymentDate": "2026-01-16",
    "status": "Paid"
  },
  {
    "id": "rr_009",
    "project": "Distribution Hub Materials Supply",
    "client": "Client AK",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG-UAE",
    "description": "50% on completion",
    "amountKES": 1679371.44,
    "amountUSD": 13018.38,
    "invoiceDate": "2026-02-13",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_010",
    "project": "Substation Upgrade Works",
    "client": "Client AI",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SDG",
    "description": "Monthly retainer",
    "amountKES": 0.0,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_011",
    "project": "Storage Facility Masterplanning",
    "client": "Client P",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SDG",
    "description": "Advance payment",
    "amountKES": 1068104.91,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_012",
    "project": "Logistics Centre Detailed Design",
    "client": "Client U",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG",
    "description": "Interim certificate",
    "amountKES": 5205964.07,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_013",
    "project": "Warehouse Design Review",
    "client": "Client AL",
    "division": "EA",
    "divisionName": "Electrical & Automation",
    "billingEntity": "SDG",
    "description": "Milestone payment",
    "amountKES": 2637305.31,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_014",
    "project": "Pipeline Materials Supply",
    "client": "Client AK",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "SDG",
    "description": "IPC 02",
    "amountKES": 0.0,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_015",
    "project": "Terminal Materials Supply",
    "client": "Client K",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SDG",
    "description": "IPC 02",
    "amountKES": 9376880.41,
    "amountUSD": 0,
    "invoiceDate": "2025-12-01",
    "paymentDate": "2026-01-16",
    "status": "Paid"
  },
  {
    "id": "rr_016",
    "project": "Terminal Feasibility Study",
    "client": "Client AI",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SDG",
    "description": "Advance payment",
    "amountKES": 5168585.77,
    "amountUSD": 0,
    "invoiceDate": "2025-12-01",
    "paymentDate": "2026-01-30",
    "status": "Paid"
  },
  {
    "id": "rr_017",
    "project": "Logistics Centre Detailed Design",
    "client": "Client X",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "DIL",
    "description": "IPC 02",
    "amountKES": 532680.92,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-06",
    "status": "Paid"
  },
  {
    "id": "rr_018",
    "project": "Terminal Design Review",
    "client": "Client J",
    "division": "EA",
    "divisionName": "Electrical & Automation",
    "billingEntity": "SDG",
    "description": "Interim certificate",
    "amountKES": 4836904.94,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_019",
    "project": "Warehouse Materials Supply",
    "client": "Client M",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG",
    "description": "Interim certificate",
    "amountKES": 5515672.41,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_020",
    "project": "Processing Plant Upgrade Works",
    "client": "Client AG",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "DIL",
    "description": "Monthly retainer",
    "amountKES": 2984741.89,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-06",
    "status": "Paid"
  },
  {
    "id": "rr_021",
    "project": "Distribution Hub Detailed Design",
    "client": "Client V",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "Monthly retainer",
    "amountKES": 1589658.45,
    "amountUSD": 0,
    "invoiceDate": "2026-01-20",
    "paymentDate": "2026-02-20",
    "status": "Paid"
  },
  {
    "id": "rr_022",
    "project": "Depot Materials Supply",
    "client": "Client S",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "Interim certificate",
    "amountKES": 1215808.71,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_023",
    "project": "Pipeline Feasibility Study",
    "client": "Client AE",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "Milestone payment",
    "amountKES": 2830998.85,
    "amountUSD": 0,
    "invoiceDate": "2026-01-20",
    "paymentDate": "2026-02-20",
    "status": "Paid"
  },
  {
    "id": "rr_024",
    "project": "Jetty Upgrade Works",
    "client": "Client AE",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "DIL",
    "description": "Advance payment",
    "amountKES": 1460576.22,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_025",
    "project": "Storage Facility Technical Audit",
    "client": "Client N",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "DIL",
    "description": "Advance payment",
    "amountKES": 4029230.02,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_026",
    "project": "Terminal Design Review",
    "client": "Client AP",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "DIL",
    "description": "IPC 01",
    "amountKES": 14312492.75,
    "amountUSD": 0,
    "invoiceDate": "2025-12-01",
    "paymentDate": "2026-01-09",
    "status": "Paid"
  },
  {
    "id": "rr_027",
    "project": "Depot Detailed Design",
    "client": "Client AG",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "DIL",
    "description": "Final account",
    "amountKES": 3334935.92,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_028",
    "project": "Pipeline Upgrade Works",
    "client": "Client AM",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "DIL",
    "description": "Monthly retainer",
    "amountKES": 926082.15,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "2026-02-13",
    "status": "Paid"
  },
  {
    "id": "rr_029",
    "project": "Pipeline Installation Works",
    "client": "Client AL",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "PEK",
    "description": "Advance payment",
    "amountKES": 158845.8,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_030",
    "project": "Logistics Centre Detailed Design",
    "client": "Client AB",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "PEK",
    "description": "Advance payment",
    "amountKES": 833149.88,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_031",
    "project": "Substation Masterplanning",
    "client": "Client M",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "PEK",
    "description": "Milestone payment",
    "amountKES": 78956.48,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_032",
    "project": "Processing Plant Materials Supply",
    "client": "Client AN",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SEAP",
    "description": "Final account",
    "amountKES": 29808.53,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-06",
    "status": "Paid"
  },
  {
    "id": "rr_033",
    "project": "Warehouse Masterplanning",
    "client": "Client AH",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "Monthly retainer",
    "amountKES": 210954.27,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_034",
    "project": "Distribution Hub Upgrade Works",
    "client": "Client Z",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "Milestone payment",
    "amountKES": 401775.81,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_035",
    "project": "Pipeline Technical Audit",
    "client": "Client V",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "Interim certificate",
    "amountKES": 231259.36,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_036",
    "project": "Terminal Materials Supply",
    "client": "Client AN",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "GCL",
    "description": "Interim certificate",
    "amountKES": 2447178.9,
    "amountUSD": 0,
    "invoiceDate": "2026-01-23",
    "paymentDate": "2025-12-11",
    "status": "Paid"
  },
  {
    "id": "rr_037",
    "project": "Access Road Site Assessment",
    "client": "Client AM",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "GCL",
    "description": "Interim certificate",
    "amountKES": 2082804.52,
    "amountUSD": 0,
    "invoiceDate": "2026-01-26",
    "paymentDate": "2026-02-20",
    "status": "Paid"
  },
  {
    "id": "rr_038",
    "project": "Warehouse PMC Services",
    "client": "Client U",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SEAP",
    "description": "IPC 01",
    "amountKES": 692678.67,
    "amountUSD": 0,
    "invoiceDate": "2025-10-01",
    "paymentDate": "2026-01-30",
    "status": "Paid"
  },
  {
    "id": "rr_039",
    "project": "Substation Upgrade Works",
    "client": "Client AE",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SEAP",
    "description": "Milestone payment",
    "amountKES": 428685.85,
    "amountUSD": 0,
    "invoiceDate": "2025-11-01",
    "paymentDate": "2026-01-30",
    "status": "Paid"
  },
  {
    "id": "rr_040",
    "project": "Processing Plant Technical Audit",
    "client": "Client R",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SEAP",
    "description": "50% on completion",
    "amountKES": 302352.85,
    "amountUSD": 0,
    "invoiceDate": "2025-12-01",
    "paymentDate": "2026-01-30",
    "status": "Paid"
  },
  {
    "id": "rr_041",
    "project": "Processing Plant PMC Services",
    "client": "Client AK",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SEAP",
    "description": "Interim certificate",
    "amountKES": 446807.6,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_042",
    "project": "Logistics Centre Design Review",
    "client": "Client L",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "GCL",
    "description": "IPC 01",
    "amountKES": 475144.03,
    "amountUSD": 0,
    "invoiceDate": "2026-01-31",
    "paymentDate": "2026-02-11",
    "status": "Paid"
  },
  {
    "id": "rr_043",
    "project": "Jetty Technical Audit",
    "client": "Client G",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "GCL",
    "description": "Advance payment",
    "amountKES": 162160.82,
    "amountUSD": 0,
    "invoiceDate": "2026-01-05",
    "paymentDate": "2026-01-13",
    "status": "Paid"
  },
  {
    "id": "rr_044",
    "project": "Warehouse Installation Works",
    "client": "Client Q",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "SFAB",
    "description": "Monthly retainer",
    "amountKES": 268231.79,
    "amountUSD": 0,
    "invoiceDate": "2026-03-04",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_045",
    "project": "Access Road Detailed Design",
    "client": "Client V",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "Dev",
    "description": "Final account",
    "amountKES": 5160176.36,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_046",
    "project": "Depot Construction Supervision",
    "client": "Client N",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SDG",
    "description": "Milestone payment",
    "amountKES": 544594.73,
    "amountUSD": 4221.66,
    "invoiceDate": "2025-12-01",
    "paymentDate": "2026-01-16",
    "status": "Paid"
  },
  {
    "id": "rr_047",
    "project": "Substation Design Review",
    "client": "Client AK",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SDG",
    "description": "50% on completion",
    "amountKES": 765952.1,
    "amountUSD": 5937.61,
    "invoiceDate": "2025-12-01",
    "paymentDate": "2026-02-06",
    "status": "Paid"
  },
  {
    "id": "rr_048",
    "project": "Jetty Masterplanning",
    "client": "Client AN",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "SFAB",
    "description": "Final account",
    "amountKES": 175488.46,
    "amountUSD": 0,
    "invoiceDate": "2026-02-18",
    "paymentDate": "2026-02-18",
    "status": "Paid"
  },
  {
    "id": "rr_049",
    "project": "Jetty Detailed Design",
    "client": "Client AP",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "SFAB",
    "description": "50% on completion",
    "amountKES": 59488.65,
    "amountUSD": 0,
    "invoiceDate": "2026-03-04",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_050",
    "project": "Pipeline Masterplanning",
    "client": "Client E",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SDG-UAE",
    "description": "Milestone payment",
    "amountKES": 9533426.44,
    "amountUSD": 73902.53,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-20",
    "status": "Paid"
  },
  {
    "id": "rr_051",
    "project": "Access Road Site Assessment",
    "client": "Client AP",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SDG-UAE",
    "description": "IPC 01",
    "amountKES": 1535751.72,
    "amountUSD": 11905.05,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-20",
    "status": "Paid"
  },
  {
    "id": "rr_052",
    "project": "Jetty Installation Works",
    "client": "Client J",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SFAB",
    "description": "50% on completion",
    "amountKES": 377431.03,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_053",
    "project": "Substation Materials Supply",
    "client": "Client B",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SFAB",
    "description": "Milestone payment",
    "amountKES": 253866.25,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_054",
    "project": "Terminal Technical Audit",
    "client": "Client Y",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SFAB",
    "description": "50% on completion",
    "amountKES": 404695.25,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_055",
    "project": "Jetty Design Review",
    "client": "Client M",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SFAB",
    "description": "IPC 02",
    "amountKES": 329422.09,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_056",
    "project": "Access Road Consultancy Services",
    "client": "Client AA",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SFAB",
    "description": "Interim certificate",
    "amountKES": 254491.11,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_057",
    "project": "Substation Consultancy Services",
    "client": "Client F",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SFAB",
    "description": "Final account",
    "amountKES": 231629.76,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_058",
    "project": "Depot Installation Works",
    "client": "Client AF",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SFAB",
    "description": "Advance payment",
    "amountKES": 418329.57,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_059",
    "project": "Pipeline Technical Audit",
    "client": "Client AK",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SFAB",
    "description": "Monthly retainer",
    "amountKES": 135998.11,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_060",
    "project": "Depot Materials Supply",
    "client": "Client F",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "Dev",
    "description": "50% on completion",
    "amountKES": 3747668.9,
    "amountUSD": 29051.7,
    "invoiceDate": "2026-02-01",
    "paymentDate": "2026-03-06",
    "status": "Paid"
  },
  {
    "id": "rr_061",
    "project": "Jetty Installation Works",
    "client": "Client AI",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "Dev",
    "description": "IPC 02",
    "amountKES": 5403814.23,
    "amountUSD": 41890.03,
    "invoiceDate": "2026-02-01",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_062",
    "project": "Storage Facility Technical Audit",
    "client": "Client X",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SEP",
    "description": "Milestone payment",
    "amountKES": 656576.49,
    "amountUSD": 0,
    "invoiceDate": "2025-12-01",
    "paymentDate": "2026-01-23",
    "status": "Paid"
  },
  {
    "id": "rr_063",
    "project": "Logistics Centre Consultancy Services",
    "client": "Client AE",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SEP",
    "description": "Final account",
    "amountKES": 796360.49,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-20",
    "status": "Paid"
  },
  {
    "id": "rr_064",
    "project": "Bridge Feasibility Study",
    "client": "Client E",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "Civil & Infra",
    "description": "Interim certificate",
    "amountKES": 508995.6,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_065",
    "project": "Pipeline Detailed Design",
    "client": "Client U",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "Dev",
    "description": "Milestone payment",
    "amountKES": 469046.09,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_066",
    "project": "Access Road Upgrade Works",
    "client": "Client A",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SFAB",
    "description": "Final account",
    "amountKES": 12553.18,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_067",
    "project": "Substation Design Review",
    "client": "Client X",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SFAB",
    "description": "Milestone payment",
    "amountKES": 17436.48,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_068",
    "project": "Jetty Upgrade Works",
    "client": "Client T",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SFAB",
    "description": "Advance payment",
    "amountKES": 36667.21,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_069",
    "project": "Bridge Masterplanning",
    "client": "Client AE",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "Dev",
    "description": "Milestone payment",
    "amountKES": 452636.72,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_070",
    "project": "Warehouse Consultancy Services",
    "client": "Client AO",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SP&A",
    "description": "IPC 01",
    "amountKES": 1286527.66,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-27",
    "status": "Paid"
  },
  {
    "id": "rr_071",
    "project": "Substation Feasibility Study",
    "client": "Client P",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "Dev",
    "description": "Interim certificate",
    "amountKES": 1704069.61,
    "amountUSD": 0,
    "invoiceDate": "2026-02-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_072",
    "project": "Pipeline Design Review",
    "client": "Client X",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "Civil & Infra",
    "description": "Monthly retainer",
    "amountKES": 131534.86,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_073",
    "project": "Storage Facility PMC Services",
    "client": "Client AK",
    "division": "UNASSIGNED",
    "divisionName": "Unassigned",
    "billingEntity": "SDG",
    "description": "Interim certificate",
    "amountKES": 8176170.4,
    "amountUSD": 63381.17,
    "invoiceDate": "2025-12-01",
    "paymentDate": "2026-01-09",
    "status": "Paid"
  },
  {
    "id": "rr_074",
    "project": "Bridge PMC Services",
    "client": "Client D",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SDG",
    "description": "IPC 02",
    "amountKES": 3821025.08,
    "amountUSD": 29620.35,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-01-09",
    "status": "Paid"
  },
  {
    "id": "rr_075",
    "project": "Processing Plant PMC Services",
    "client": "Client AE",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG",
    "description": "Milestone payment",
    "amountKES": 15299282.22,
    "amountUSD": 118599.09,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-01-09",
    "status": "Paid"
  },
  {
    "id": "rr_076",
    "project": "Depot Site Assessment",
    "client": "Client J",
    "division": "EA",
    "divisionName": "Electrical & Automation",
    "billingEntity": "SDG",
    "description": "IPC 02",
    "amountKES": 518307.26,
    "amountUSD": 4017.89,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-01-09",
    "status": "Paid"
  },
  {
    "id": "rr_077",
    "project": "Substation Masterplanning",
    "client": "Client C",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SDG",
    "description": "IPC 02",
    "amountKES": 12600138.75,
    "amountUSD": 97675.49,
    "invoiceDate": "2026-02-01",
    "paymentDate": "2026-02-13",
    "status": "Paid"
  },
  {
    "id": "rr_078",
    "project": "Bridge Detailed Design",
    "client": "Client AI",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG",
    "description": "Final account",
    "amountKES": 17428780.91,
    "amountUSD": 135106.83,
    "invoiceDate": "2026-02-01",
    "paymentDate": "2026-02-13",
    "status": "Paid"
  },
  {
    "id": "rr_079",
    "project": "Jetty Consultancy Services",
    "client": "Client AA",
    "division": "EA",
    "divisionName": "Electrical & Automation",
    "billingEntity": "SDG",
    "description": "Monthly retainer",
    "amountKES": 590464.09,
    "amountUSD": 4577.24,
    "invoiceDate": "2026-02-01",
    "paymentDate": "2026-02-13",
    "status": "Paid"
  },
  {
    "id": "rr_080",
    "project": "Logistics Centre Installation Works",
    "client": "Client T",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SDG",
    "description": "Final account",
    "amountKES": 2646916.43,
    "amountUSD": 20518.73,
    "invoiceDate": "2026-03-01",
    "paymentDate": "2026-02-13",
    "status": "Paid"
  },
  {
    "id": "rr_081",
    "project": "Pipeline PMC Services",
    "client": "Client AM",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG",
    "description": "IPC 01",
    "amountKES": 19484021.71,
    "amountUSD": 151038.93,
    "invoiceDate": "2026-03-01",
    "paymentDate": "2026-02-13",
    "status": "Paid"
  },
  {
    "id": "rr_082",
    "project": "Substation Design Review",
    "client": "Client Y",
    "division": "EA",
    "divisionName": "Electrical & Automation",
    "billingEntity": "SDG",
    "description": "50% on completion",
    "amountKES": 387636.29,
    "amountUSD": 3004.93,
    "invoiceDate": "2026-03-01",
    "paymentDate": "2026-02-13",
    "status": "Paid"
  },
  {
    "id": "rr_083",
    "project": "Substation Site Assessment",
    "client": "Client U",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG-UAE",
    "description": "Final account",
    "amountKES": 551430.25,
    "amountUSD": 4274.65,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-20",
    "status": "Paid"
  },
  {
    "id": "rr_084",
    "project": "Bridge Construction Supervision",
    "client": "Client AM",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "Dev",
    "description": "Advance payment",
    "amountKES": 315177.44,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_085",
    "project": "Jetty Materials Supply",
    "client": "Client AB",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEP",
    "description": "Monthly retainer",
    "amountKES": 1555176.37,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-20",
    "status": "Paid"
  },
  {
    "id": "rr_086",
    "project": "Jetty Materials Supply",
    "client": "Client AH",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "SFAB",
    "description": "Interim certificate",
    "amountKES": 105005.41,
    "amountUSD": 0,
    "invoiceDate": "2026-03-02",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_087",
    "project": "Warehouse Upgrade Works",
    "client": "Client N",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG",
    "description": "Monthly retainer",
    "amountKES": 3925171.62,
    "amountUSD": 0,
    "invoiceDate": "2026-01-01",
    "paymentDate": "2026-02-20",
    "status": "Paid"
  },
  {
    "id": "rr_088",
    "project": "Access Road Detailed Design",
    "client": "Client Y",
    "division": "EA",
    "divisionName": "Electrical & Automation",
    "billingEntity": "SDG",
    "description": "Final account",
    "amountKES": 481811.2,
    "amountUSD": 0,
    "invoiceDate": "2026-03-01",
    "paymentDate": "2026-03-09",
    "status": "Pending"
  },
  {
    "id": "rr_089",
    "project": "Jetty Site Assessment",
    "client": "Client W",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "Civil & Infra",
    "description": "50% on completion",
    "amountKES": 190498.9,
    "amountUSD": 0,
    "invoiceDate": "2026-03-01",
    "paymentDate": "2026-03-13",
    "status": "Paid"
  },
  {
    "id": "rr_090",
    "project": "Logistics Centre Technical Audit",
    "client": "Client L",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "Civil & Infra",
    "description": "Interim certificate",
    "amountKES": 8142751.93,
    "amountUSD": 0,
    "invoiceDate": "2026-03-05",
    "paymentDate": "2026-03-06",
    "status": "Paid"
  },
  {
    "id": "rr_091",
    "project": "Pipeline Feasibility Study",
    "client": "Client G",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SFAB",
    "description": "IPC 01",
    "amountKES": 3010452.93,
    "amountUSD": 0,
    "invoiceDate": "2026-03-11",
    "paymentDate": "2026-03-12",
    "status": "Paid"
  },
  {
    "id": "rr_092",
    "project": "Access Road Feasibility Study",
    "client": "Client O",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SDG",
    "description": "Advance payment",
    "amountKES": 277891.81,
    "amountUSD": 0,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "nan"
  },
  {
    "id": "rr_093",
    "project": "Logistics Centre Site Assessment",
    "client": "Client J",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "Milestone payment",
    "amountKES": 1182425.08,
    "amountUSD": 9166.09,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "nan"
  },
  {
    "id": "rr_094",
    "project": "Storage Facility Feasibility Study",
    "client": "Client Q",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG-UAE",
    "description": "Monthly retainer",
    "amountKES": 3017732.31,
    "amountUSD": 23393.27,
    "invoiceDate": "2026-03-13",
    "paymentDate": "",
    "status": "nan"
  },
  {
    "id": "rr_095",
    "project": "Substation PMC Services",
    "client": "Client H",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SEAP",
    "description": "Interim certificate",
    "amountKES": 815470.08,
    "amountUSD": 0,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_096",
    "project": "Substation Feasibility Study",
    "client": "Client AF",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SEAP",
    "description": "Interim certificate",
    "amountKES": 208276.5,
    "amountUSD": 0,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_097",
    "project": "Terminal Materials Supply",
    "client": "Client N",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "Monthly retainer",
    "amountKES": 233391.92,
    "amountUSD": 0,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_098",
    "project": "Access Road Design Review",
    "client": "Client Y",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "IPC 02",
    "amountKES": 383774.1,
    "amountUSD": 0,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_099",
    "project": "Substation PMC Services",
    "client": "Client AF",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SEAP",
    "description": "IPC 01",
    "amountKES": 26015.72,
    "amountUSD": 0,
    "invoiceDate": "2026-03-25",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_100",
    "project": "Logistics Centre Design Review",
    "client": "Client AK",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SEAP",
    "description": "IPC 01",
    "amountKES": 10838.22,
    "amountUSD": 0,
    "invoiceDate": "2026-03-25",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_101",
    "project": "Jetty Materials Supply",
    "client": "Client G",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SEAP",
    "description": "50% on completion",
    "amountKES": 17845.07,
    "amountUSD": 0,
    "invoiceDate": "2026-03-25",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_102",
    "project": "Depot Installation Works",
    "client": "Client V",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SEAP",
    "description": "Milestone payment",
    "amountKES": 7879.23,
    "amountUSD": 0,
    "invoiceDate": "2026-03-25",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_103",
    "project": "Jetty Installation Works",
    "client": "Client AA",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "Advance payment",
    "amountKES": 639371.87,
    "amountUSD": 0,
    "invoiceDate": "2026-03-18",
    "paymentDate": "2026-03-26",
    "status": "Paid"
  },
  {
    "id": "rr_104",
    "project": "Processing Plant Construction Supervision",
    "client": "Client Y",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SEAP",
    "description": "Final account",
    "amountKES": 2729400.85,
    "amountUSD": 0,
    "invoiceDate": "2026-03-18",
    "paymentDate": "2026-03-26",
    "status": "Paid"
  },
  {
    "id": "rr_105",
    "project": "Logistics Centre Design Review",
    "client": "Client AN",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "DIL",
    "description": "Interim certificate",
    "amountKES": 2600869.59,
    "amountUSD": 0,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_106",
    "project": "Bridge Feasibility Study",
    "client": "Client G",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SEAP",
    "description": "Advance payment",
    "amountKES": 3244915.84,
    "amountUSD": 0,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_107",
    "project": "Storage Facility Masterplanning",
    "client": "Client A",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SEAP",
    "description": "Monthly retainer",
    "amountKES": 159667.89,
    "amountUSD": 0,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_108",
    "project": "Warehouse PMC Services",
    "client": "Client X",
    "division": "EA",
    "divisionName": "Electrical & Automation",
    "billingEntity": "SDG",
    "description": "IPC 01",
    "amountKES": 260085.43,
    "amountUSD": 0,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_109",
    "project": "Storage Facility Consultancy Services",
    "client": "Client G",
    "division": "EA",
    "divisionName": "Electrical & Automation",
    "billingEntity": "SDG",
    "description": "50% on completion",
    "amountKES": 666361.56,
    "amountUSD": 0,
    "invoiceDate": "2026-03-19",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_110",
    "project": "Processing Plant Upgrade Works",
    "client": "Client T",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "DIL",
    "description": "50% on completion",
    "amountKES": 0,
    "amountUSD": 0,
    "invoiceDate": "2026-03-18",
    "paymentDate": "2026-03-23",
    "status": "Paid"
  },
  {
    "id": "rr_111",
    "project": "Distribution Hub Site Assessment",
    "client": "Client AG",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SEAP",
    "description": "Milestone payment",
    "amountKES": 604738.0,
    "amountUSD": 0,
    "invoiceDate": "2026-03-18",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_112",
    "project": "Distribution Hub Site Assessment",
    "client": "Client P",
    "division": "CI",
    "divisionName": "Civil & Infrastructure",
    "billingEntity": "SEAP",
    "description": "IPC 01",
    "amountKES": 417730.94,
    "amountUSD": 0,
    "invoiceDate": "2026-03-18",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_113",
    "project": "Warehouse Site Assessment",
    "client": "Client H",
    "division": "ALM",
    "divisionName": "Asset & Lifecycle Management",
    "billingEntity": "DIL",
    "description": "50% on completion",
    "amountKES": 0,
    "amountUSD": 0,
    "invoiceDate": "2026-03-23",
    "paymentDate": "",
    "status": "Pending"
  },
  {
    "id": "rr_114",
    "project": "Pipeline Installation Works",
    "client": "Client AP",
    "division": "DM",
    "divisionName": "Development Management",
    "billingEntity": "SEAP",
    "description": "IPC 02",
    "amountKES": 0,
    "amountUSD": 5000.0,
    "invoiceDate": "",
    "paymentDate": "",
    "status": "nan"
  },
  {
    "id": "rr_115",
    "project": "Access Road PMC Services",
    "client": "Client W",
    "division": "MF",
    "divisionName": "Mechanical & Fabrication",
    "billingEntity": "SDG-UAE",
    "description": "IPC 01",
    "amountKES": 0,
    "amountUSD": 11600.0,
    "invoiceDate": "2026-03-23",
    "paymentDate": "2026-03-27",
    "status": "Paid"
  }
];

/* Bootstrap DB.realizedRevenue from seed if not already populated */
if (typeof DB !== 'undefined' && !DB.realizedRevenue) {
  DB.realizedRevenue = JSON.parse(JSON.stringify(REALIZED_REVENUE_SEED));
}

/* ══════════════════════════════════════════
   RISK SIGNALS — 15 organisational risks
   Each deal can carry multiple risk flags.
══════════════════════════════════════════ */
const RISKS = [
  { code:'FUND',     label:'Funding Risk',              group:'Financial',   col:'#dc2626', desc:'Donor/DFI or client budget may not materialise or disbursement is delayed' },
  { code:'PAY',      label:'Payment Risk',              group:'Financial',   col:'#b45309', desc:'Client has history of late payment or complex payment processes' },
  { code:'GEO',      label:'Geopolitical Risk',         group:'Political',   col:'#7c3aed', desc:'Regional instability, sanctions, conflict, or security risk affecting delivery' },
  { code:'POL_LOC',  label:'Local Political Risk',      group:'Political',   col:'#9333ea', desc:'Elections, ministerial reshuffles, or policy changes blocking approval' },
  { code:'PROC',     label:'Slow Procurement Process',  group:'Commercial',  col:'#2563eb', desc:'Lengthy or unpredictable tender and approval timelines' },
  { code:'REL',      label:'Weak Client Relationship',  group:'Commercial',  col:'#1d4ed8', desc:'Relationship is thin, single-point, or dependent on one champion' },
  { code:'REG',      label:'Regulatory Risks',          group:'Delivery',    col:'#0891b2', desc:'Permits, environmental approvals, or licences delayed or at risk of denial' },
  { code:'PRESENCE', label:'Local Presence Gap',        group:'Delivery',    col:'#059669', desc:'No office, local staff, or established subcontractors in the market' },
];
